# Generated by Django 3.2.18 on 2023-05-01 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthToken',
        ),
    ]
